export const meals = [
  {
    id: 284934,
    title: "Pizza Sub (12)",
    image: "https://images.spoonacular.com/file/wximages/284934-312x231.jpg",
    imageType: "jpg",
    restaurantChain: "East of Chicago",
    servingSize: "157g",
    readableServingSize: "6 oz",
    price: 100,
    servings: {
      number: 1,
      size: 157,
      unit: "g",
    },
  },
  {
    id: 418834,
    title: "Chicken Wing",
    image: "https://images.spoonacular.com/file/wximages/418834-312x231.png",
    imageType: "png",
    restaurantChain: "Bojangles",
    servingSize: "1 pc",
    readableServingSize: "1 pc",
    price: 120,
    servings: {
      number: 1,
      size: 1,
      unit: "pc",
    },
  },
  {
    id: 295357,
    title: "Pie (Strawberry)",
    image: "https://images.spoonacular.com/file/wximages/295357-312x231.jpg",
    imageType: "jpg",
    restaurantChain: "Eat n Park",
    servingSize: "1 slice",
    readableServingSize: "1 slice",
    price: 200,
    servings: {
      number: 1,
      size: 1,
      unit: "slice",
    },
  },
  {
    id: 421936,
    title: "Cheesecake",
    image: "https://images.spoonacular.com/file/wximages/421936-312x231.jpg",
    imageType: "jpg",
    restaurantChain: "Captain D's",
    servingSize: "1 slice",
    readableServingSize: "1 slice",
    price: 110,
    servings: {
      number: 1,
      size: 1,
      unit: "slice",
    },
  },
  {
    id: 306979,
    title: "Oak Roasted Salmon on Ponzu Salad",
    image: "https://spoonacular.com/menuItemImages/grilled-salmon.jpg",
    imageType: "jpg",
    restaurantChain: "Sammys Woodfired Pizza",
    servingSize: "1.5 cups",
    readableServingSize: "1.5cups",
    price: 105,
    servings: {
      number: 1,
      size: 1.5,
      unit: "cups",
    },
  },
  {
    id: 355521,
    title: "Pan Roasted Citrus Salmon w/ Grilled Asparagus",
    image: "https://spoonacular.com/menuItemImages/grilled-salmon.jpg",
    imageType: "jpg",
    restaurantChain: "Gordon Biersch Brewery",
    servingSize: "1 serving",
    readableServingSize: "1 serving",
    price: 300,
    servings: {
      number: 1,
      size: 1,
      unit: "serving",
    },
  },
  {
    id: 355388,
    title: "Gorgonzola Pear Salad w/ Roasted Jalapeno Ranch Dressing",
    image:
      "https://spoonacular.com/menuItemImages/pear-goat-cheese-pecan-salad.jpg",
    imageType: "jpg",
    restaurantChain: "Gordon Biersch Brewery",
    servingSize: "1 salad",
    readableServingSize: "1 salad",
    price: 500,
    servings: {
      number: 1,
      size: 1,
      unit: "salad",
    },
  },
  {
    id: 288374,
    title: "Roasted Garlic Potatoes",
    image:
      "https://spoonacular.com/cdn/ingredients_100x100/potatoes-yukon-gold.jpg",
    imageType: "jpg",
    restaurantChain: "KooKooRoo",
    servingSize: "5oz",
    readableServingSize: "5 oz",
    price: 123,
    servings: {
      number: 1,
      size: 5,
      unit: "oz",
    },
  },
  {
    id: 227035,
    title: "Strawberry Bread",
    image: "https://images.spoonacular.com/file/wximages/227035-312x231.jpg",
    imageType: "jpg",
    restaurantChain: "Bob Evans",
    servingSize: "62g",
    readableServingSize: "2 oz",
    price: 159,
    servings: {
      number: 1,
      size: 62,
      unit: "g",
    },
  },
];
